/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SistemadeInscripcion;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import SistemadeInscripcion.SistemadeInscripcion;
import GestordeUsuarios.GestordeUsuarios;

/**
 *
 * @author andre
 */
public class MatricularPanel extends javax.swing.JPanel {

    private SistemadeInscripcion sistema;

    /**
     * Creates new form MatricularPanel
     */
    public MatricularPanel(SistemadeInscripcion sistema) {
        this.sistema = sistema;
        initComponents();

        String[] cursos = {
            "Fútbol = Lunes 6pm",
            "Costura = Sábado 10am",
            "Guitarra = Sábado 3pm",
            "Manualidades = Martes 2pm",
            "Muay Thai = Sábado 7pm"
        };

        for (String curso : cursos) {
            comboCursos.addItem(curso);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCursos = new javax.swing.JComboBox<>();
        txtCedula = new javax.swing.JTextField();
        btnMatricular = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        btnMatricular.setText("Matricular");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
        String cursoSeleccionado = (String) comboCursos.getSelectedItem();
        String cedula = txtCedula.getText().trim();

        if (cedula.isEmpty()) {
            lblMensaje.setText("Por favor ingrese una cédula.");
            lblMensaje.setForeground(java.awt.Color.RED);
            return;
        }

        int cursoIndex = comboCursos.getSelectedIndex() + 1;

        if (sistema.obtenerGestorUsuarios().obtenerUsuarioPorCedula(cedula) == null) {
            lblMensaje.setText("Usuario no registrado.");
            lblMensaje.setForeground(java.awt.Color.RED);
            return;
        }

        sistema.matricularUsuario(cursoIndex, cedula);
        lblMensaje.setText("Matrícula procesada para " + cedula);
        lblMensaje.setForeground(java.awt.Color.GREEN);
        txtCedula.setText("");
    }//GEN-LAST:event_btnMatricularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatricular;
    private javax.swing.JComboBox<String> comboCursos;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
